### ISSUE TITLE
Enhancement: Parse and report on all markdown in folder

### ISSUE THREAD

**Issue by jwood803** [btford/readme-good#1]
Can have the option to go through all the markdown files found in the preferred folder and give suggestions on each file.

**Comment by btford** [comment]
FYI this is the default behavior of https://github.com/btford/write-good

Some of the checks might only make sense for a readme though; for instance, the current implementation of this module checks for the presence of a few specific headers (license, see also, etc...) that I wouldn't expect to be in other markdown files. Maybe the right thing to do is check that among all markdown files, at least one of them satisfies each constraint.

I'll think on it. Thanks!

**Comment by jwood803** [comment]
Ahh, that's true. Maybe it can also give a warning message if it finds a specific header multiple times? Though, there may be times where that's needed.
